name: skillr
description: "A Career Recommender App!!."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator : ^4.2.3
  dart_openai: ^5.0.0
  http: ^1.1.2
  url_launcher: ^6.2.1
  flutter_spinkit: ^5.2.0
  chat_bubbles: ^1.5.0
  flutter_markdown: ^0.6.18+2
  markdown_widget: ^2.3.1
  adaptive_theme: ^3.4.1
  flutter_share: ^2.0.0
  settings_ui: ^2.0.2
  image: ^4.1.3
  image_gallery_saver: ^2.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
 
  assets:
    - assets/
    - assets/data/
    - assets/images/
fonts:
    - family: TeXGyreBonum
      fonts:
        - asset: fonts/texgyrebonum.ttf