name: skillr
description: "A Career Recommending app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator : ^4.2.3
  dart_openai: ^5.0.0
  http: ^1.2.0
  url_launcher: ^6.2.4
  chewie: ^1.7.5
  rive: ^0.12.3
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2

  dynamic_background: ^0.1.3
  video_player: ^2.8.2
  flutter_spinkit: ^5.2.0
  chat_bubbles: ^1.6.0
  flutter_markdown: ^0.6.18+2
  markdown_widget: ^2.3.2+3 
  adaptive_theme: ^3.6.0
  flutter_share: ^2.0.0
  settings_ui: ^2.0.2
  image: ^4.1.3
  image_gallery_saver: ^2.0.3
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
 
  assets:
    - assets/
    - assets/data/
    - assets/images/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/

fonts:
    - family: TeXGyreBonum
      fonts:
        - asset: fonts/texgyrebonum.ttf

    - family: Inter
      fonts: 
       - asset: fonts/Inter-Regular.ttf
       - asset: fonts/Inter-SemiBold.otf
         weights: 600 

    - family: Poppins
      fonts: 
      - asset: fonts/Poppins-bold.tff
        weight: 700