// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1t11qQ8K2FHhMD1UfOhLSs4Ma6tH0Xxo',
    appId: '1:333274558089:web:1617cf1da1bfa67df1a058',
    messagingSenderId: '333274558089',
    projectId: 'skillr-io',
    authDomain: 'skillr-io.firebaseapp.com',
    databaseURL: 'https://skillr-io-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillr-io.appspot.com',
    measurementId: 'G-LV4RR6WR0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jE4JpJdodAoYmXAj3wqQasQvL69lxO0',
    appId: '1:333274558089:android:758175b7ea99020cf1a058',
    messagingSenderId: '333274558089',
    projectId: 'skillr-io',
    databaseURL: 'https://skillr-io-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillr-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsVDTSolth0yMDpCfBpnr-ztF6I332ZSI',
    appId: '1:333274558089:ios:2c8210c89e7750fff1a058',
    messagingSenderId: '333274558089',
    projectId: 'skillr-io',
    databaseURL: 'https://skillr-io-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillr-io.appspot.com',
    iosBundleId: 'com.example.careerRec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsVDTSolth0yMDpCfBpnr-ztF6I332ZSI',
    appId: '1:333274558089:ios:c7efb8401a717b1cf1a058',
    messagingSenderId: '333274558089',
    projectId: 'skillr-io',
    databaseURL: 'https://skillr-io-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillr-io.appspot.com',
    iosBundleId: 'com.example.careerRec.RunnerTests',
  );
}
